name: passwordmanager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3 
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
